# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ab282f1ad5d8cf6d37e776e885dc16fd96015a1d5845a5e71f9d28c4b490b6e6b79c349aae048c8e08ab85a1881783a9da2653b7dd74b26f7b88aa2e6e2baf4

test:
  secret_key_base: ee4c285a6a37a1d36213353b8f625cb66d9a511dc366a7c12dfdaaabef4f65d06cdce394550c320499c18074a821b967014c0e99301cd39192f9cf08df5c8819

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
